/* eslint-disable import/no-duplicates */
/* eslint-disable import/newline-after-import */
// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName
import { application } from './application'
import CommentairesController from './commentaires_controller'
import HelloController from './hello_controller'

application.register('commentaires', CommentairesController)
application.register('hello', HelloController)
